apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: flight-prediction
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'flask'
        static_configs:
          - targets: ['flask.flight-prediction:5001']
        metrics_path: '/metrics'
      - job_name: 'kafka'
        static_configs:
          - targets: ['kafka-exporter.flight-prediction:9308']
      - job_name: 'cassandra'
        static_configs:
          - targets: ['cassandra-exporter.flight-prediction:9500']
